spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/smartcart_order?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: root
    password: Sindhu@07
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true


server:
  port: 8088


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true


payment:
  service:
    url: http://payment-service

delivery:
  service:
    url: http://delivery-service
